name: lan_party_planner
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Utils
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  
  # Supabase (NOVO!)
  supabase_flutter: ^2.5.0
  
  # Images
  image_picker: ^1.0.7
  flutter_image_compress: ^2.2.0
  
  # Crypto
  crypto: ^3.0.3
  http: ^1.2.1
  
  # Icons
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/PNGs/logoIASemfundo.png
    - assets/PNGs/logoIA.png
    - assets/privacidade.md
    - assets/termos.md

flutter_icons:
  android: true
  ios: true
  image_path: "assets/PNGs/logoIA.png"